// <auto-generated />
using System;
using Bnp.Paribas.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bnp.Paribas.Infra.Migrations
{
    [DbContext(typeof(BnpContext))]
    [Migration("20260521025611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Bnp.Paribas.Domain.Entity.MovimentoManual", b =>
                {
                    b.Property<int>("DatMes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatAno")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NumLancamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodCosif")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodProduto")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DatMovimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesDescricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValValor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DatMes", "DatAno", "NumLancamento");

                    b.HasIndex("CodProduto", "CodCosif");

                    b.ToTable("MovimentoManual", (string)null);
                });

            modelBuilder.Entity("Bnp.Paribas.Domain.Entity.Produto", b =>
                {
                    b.Property<string>("CodProduto")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DesProduto")
                        .HasColumnType("varchar(100)");

                    b.Property<char?>("StaStatus")
                        .HasColumnType("char(1)");

                    b.HasKey("CodProduto");

                    b.ToTable("Produto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Produto_StaStatus", "StaStatus IN ('A', 'I')");
                        });
                });

            modelBuilder.Entity("Bnp.Paribas.Domain.Entity.ProdutoCosif", b =>
                {
                    b.Property<string>("CodProduto")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodCosif")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodClassificacao")
                        .HasColumnType("varchar(20)");

                    b.Property<char?>("StaStatus")
                        .HasColumnType("char(1)");

                    b.HasKey("CodProduto", "CodCosif");

                    b.ToTable("ProdutoCosif", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProdutoCosif_CodClassificacao", "CodClassificacao IN ('Normal', 'MTM')");

                            t.HasCheckConstraint("CK_ProdutoCosif_StaStatus", "StaStatus IN ('A', 'I')");
                        });
                });

            modelBuilder.Entity("Bnp.Paribas.Domain.Entity.MovimentoManual", b =>
                {
                    b.HasOne("Bnp.Paribas.Domain.Entity.ProdutoCosif", "ProdutoCosif")
                        .WithMany()
                        .HasForeignKey("CodProduto", "CodCosif")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoCosif");
                });

            modelBuilder.Entity("Bnp.Paribas.Domain.Entity.ProdutoCosif", b =>
                {
                    b.HasOne("Bnp.Paribas.Domain.Entity.Produto", "Produto")
                        .WithMany("ProdutoCosifs")
                        .HasForeignKey("CodProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Bnp.Paribas.Domain.Entity.Produto", b =>
                {
                    b.Navigation("ProdutoCosifs");
                });
#pragma warning restore 612, 618
        }
    }
}
